### ISSUE TITLE
Typo in BED_FILES/hg38/v22/Groups.bed

### ISSUE THREAD

**Issue by Botvinnik92** [parvathisudha/Targeted-Panel-Analysis#19]
Greetings,
I have just found a typo while analysing with the panel. In the `Groups.bed` file that belongs to the `hg38/v22` setup, line 160 should be:
`chr11	118436498	118522184	KMT2A	groups` 
instead of 
`chr11	118436498	118522184	IGHV8-51-1	groups`

This leads to the `KMT2A` region in `chr11` being erroneously called as `IGHV8-51-1` in Tarpan:
![before](https://github.com/user-attachments/assets/4d470576-8ef2-43e1-ade4-c7050199313a)

I have checked this with the `Targeted_regions.bed` and other BED files and it is corrected there, as well as in other versions. I guess there was a mistake when switching from `v21` to `v22`, as the lines with `MLL  ->  KMT2A` and `IGHVIII-51-1  ->  IGHV8-51-1` follow each other in the changelog.

After editing the `Groups.bed` file and updating the Tarpan database, the issue is already solved:
![after](https://github.com/user-attachments/assets/a5159204-a8fe-42f1-b992-e449704b6149)

Thank you so much for you work.
Best,
David.

**Comment by parvathisudha** [comment]
Thanks for reporting this error. The Groups.bed file has been updated now.
